version: '3'

services:
  api_gateway:
    build: ./app
    container_name: api_gateway
    ports:
      - '127.0.0.1:8089:8089'
    env_file:
      - ./app/.env
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8089"
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
  db:
    image: mongo:latest
    env_file:
      - ./mongodb/.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db


volumes:
  postgres_data: