version: '3'

services:
  forms_app:
    build: ./app
    container_name: forms_app
    ports:
      - '127.0.0.1:8089:8089'
    env_file:
      - ./app/.env
    command: bash -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8089"
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.2.6
    env_file:
      - ./mongodb/.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongo_seed:
    image: mongo:3.2.6
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command: bash -c "mongoimport --host mongodb --db forms --collection form_collection --type json --file /mongo-seed/forms_collection.json --jsonArray"

volumes:
  mongodb_data_container: